### ISSUE TITLE
ponyup-init.sh on real sh 

### ISSUE THREAD

**Issue by dlqs** [ponylang/ponyup#191] opened 2021-07-19 15:42 UTC
Installating ponyup-init.sh doesn't look great with real `sh` (like on freebsd) because the ansi escape codes are printed out literally. Perhaps change the top of the script to #!/bin/bash? Or have seperate instructions for freebsd.

**Comment by SeanTAllen** [comment] 2021-07-19 15:45
if its /bin/bash at the top then it won't work on `sh` at all.

**Comment by Theodus** [comment] 2021-07-19 15:50
I think there should be a solution in the form of assigning the `DEFAULT`, `BLUE`, `RED`, etc. variables in the script to empty strings if the color escape sequences are not supported by the shell.

**Comment by SeanTAllen** [comment] 2021-07-19 15:55
Yeah this is on a per-terminal, not shell basis.

**Comment by redvers** [comment] 2021-07-27 18:44
@dlqs - Can you please let us know if you're doing this from console or via a terminal (if so which).
Also - the value of your TERM environmental variable (echo $TERM)

Thanks.

**Comment by dlqs** [comment] 2021-07-27 19:12
xterm:
![image](https://user-images.githubusercontent.com/31354724/127213631-a118154a-a8fa-457e-a1f8-1c46f244cd1f.png)

**Comment by redvers** [comment] 2021-07-28 15:44
I've installed FreeBSD and have replicated it.  Now trying to understand the delta.
Thank you for the report!

**Comment by redvers** [comment] 2021-07-28 16:20
The root of the problem is the way that bash and sh treat the contents of single and double quotes differently by default.

I'm crafting a PR to fix this - thank you :-)

**Comment by Theodus** [comment] 2021-07-28 18:57
Resolved by #192

**Closed by Theodus** 2021-07-28 18:57 UTC
